# Generated by Django 6.0.2 on 2026-02-25 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_remove_job_company_remove_job_posted_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='analyzer.role'),
        ),
        migrations.AddField(
            model_name='skill',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='analyzer.role'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddConstraint(
            model_name='salarydata',
            constraint=models.UniqueConstraint(fields=('role', 'experience_level'), name='uniq_salarydata_role_experience'),
        ),
        migrations.AddConstraint(
            model_name='skill',
            constraint=models.UniqueConstraint(fields=('role', 'name'), name='uniq_skill_per_role'),
        ),
    ]
